### ISSUE TITLE
[TASK] Publish latest version to TER

### ISSUE THREAD

**Issue by BastianBalthasarBux** [in2code-de/t3am_server#11]
Latest version v3 which is compatible to TYPO3 v10 LTS is not published to TER yet.

**Comment by sbusemann** [comment]
thanks for the hint - the version is now online

**Comment by BastianBalthasarBux** [comment]
Sorry, I have to reopen: the version info is set to 10.0.0
In fact I use it successfully with 10.4 LTS.
It's not a big problem, but has some backdraws, e.g. with upgrades on Mittwald, but I am pretty sure, also in composer setups it could cause problems.
