### ISSUE TITLE
allow TYPO3 version 9 as server

### ISSUE THREAD

**Issue by sbusemann** [in2code-de/t3am_server#2]
I as an admin, i want to use TYPO3 version 9 as a server

**Comment by ghost** [comment]
Hi Stefan, I'd be interested in using the TYPO3 version 9 of your T3AM server too. Do you already have a rough idea when you will release a new version of the server?

**Comment by sbusemann** [comment]
sorry not, we will do this at lastest, once our own website is upgraded to v9.

Feel free to create a pull request or you can speed up development with sponsoring.

**Comment by ghost** [comment]
Thank you for the feedback. I opened a pull request #3 regarding this issue.

**Comment by vertexvaar** [comment]
Resolved with PR #3
